#!/usr/bin/env bash
set -xe

#check if hugo is installed
hugo=$(command -v hugo)
if [[ -z "$hugo" ]]; then
  echo "Hugo is not installed, please do it, right now ;)"
fi

slugify () {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "$1" | iconv -t ascii//TRANSLIT | sed -E 's/'\''//g' | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z
  else
    echo "$1" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr "[:upper:]" "[:lower:]"
  fi
}

speakername=
presentationtitle=
edition=

# extract command line options
while getopts ":s:p:e:" opt; do
  case $opt in
    s)
      speakername=$OPTARG
      ;;
    p)
      presentationtitle=$OPTARG
      ;;
    e)
      edition=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [[ -z "$presentationtitle" ]] || [[ -z "$speakername" ]] || [[ -z "$edition" ]]; then
  echo "missing arguments, like -p \"Cool stuff\" -s \"Kuba Marchwicki\" -e warszawa2019"
  exit
fi

presentationslug=$(slugify "$presentationtitle")
speakerslug=$(slugify "$speakername")

presentationfile="content/sites/$edition/abstracts/$presentationslug/index.md"
speakerfile="content/sites/$edition/speakers/$speakerslug/index.md"

if [[ ! -f "$presentationfile" ]]; then
  hugo new -k abstract "$presentationfile"
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' -e "s/\${presentationtitle}/$presentationtitle/" "$presentationfile"
    sed -i '' -e "s/\${speakername}/$speakername/" "$presentationfile"
  else
    sed -i -e "s/\${presentationtitle}/$presentationtitle/" "$presentationfile"
    sed -i -e "s/\${speakername}/$speakername/" "$presentationfile"
  fi
fi

if [[ ! -f "$speakerfile" ]]; then
  hugo new -k speaker "$speakerfile"
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' -e "s/\${presentationtitle}/$presentationtitle/" "$speakerfile"
    sed -i '' -e "s/\${speakername}/$speakername/" "$speakerfile"
  else
    sed -i -e "s/\${presentationtitle}/$presentationtitle/" "$speakerfile"
    sed -i -e "s/\${speakername}/$speakername/" "$speakerfile"
  fi
fi
