image: symentis/hugo:latest

pipelines:
  default:
    - step:
        deployment: test
        script:
          - /.bin/hugo --minify --baseURL=http://test.segfault.events/
          - LFTP_PASSWORD="$SEGFAULT_TEST_FTP_SITE_PASSWD" lftp -f lftprc.default
  custom:
    go-live:
      - step:
          deployment: production
          script:
            - /.bin/hugo --minify --baseURL=http://segfault.events/
            - LFTP_PASSWORD="$SEGFAULT_FTP_SITE_PASSWD" lftp -f lftprc.deployment
